### ISSUE TITLE
[Feature] Feature to Update the data via data.json if database is non-existent or is down.

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/codebooker#179]
There should be a way of doing this.

We can do a `GET` and `PUT` request via the API to the file, data.json which contains the data.

I would include a [Update Data] button somewhere in the UI.

Then we could use some code like these snippits.

```js
const express = require('express');
const fs = require('fs');
const app = express();
const port = 3001;

app.use(express.json());

// GET request handler
app.get('/data', (req, res) => {
  fs.readFile('data.json', 'utf8', (err, data) => {
    if (err) {
      console.error(err);
      res.status(500).send('Error reading data.json');
    } else {
      res.send(data);
    }
  });
});

// POST request handler
app.post('/data', (req, res) => {
  const newData = req.body;

  fs.writeFile('data.json', JSON.stringify(newData), 'utf8', (err) => {
    if (err) {
      console.error(err);
      res.status(500).send('Error writing to data.json');
    } else {
      res.send('Data updated successfully');
    }
  });
});

app.listen(port, () => {
  console.log(`Server running on port ${port}`);
});
```

and the React client side code

```js
import React, { useEffect, useState } from 'react';

function App() {
  const [data, setData] = useState([]);

  useEffect(() => {
    fetch('/data')
      .then((response) => response.json())
      .then((data) => setData(data))
      .catch((error) => console.error(error));
  }, []);

  const handleUpdateData = () => {
    const newData = { name: 'John Doe' };

    fetch('/data', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(newData),
    })
      .then((response) => response.text())
      .then((message) => console.log(message))
      .catch((error) => console.error(error));
  };

  return (
    <div>
      <h1>Data: {data.name}</h1>
      <button onClick={handleUpdateData}>Update Data</button>
    </div>
  );
}

export default App;

**Comment by gbowne1** [comment]
This could including fixing some of #178

**Comment by Priyankaa2503** [comment]
Hi, i would like to work on this issue. Can you assign it to me?

**Comment by BlackBond06** [comment]
> Hi, i would like to work on this issue. Can you assign it to me?

Go ahead. The issue has been assigned to you.

**Comment by Priyankaa2503** [comment]
Hello, just wanted to clarify this doubt, so when i login currently there is no data in my database that is why the page is in loading state continuously? So, if is happens we need to fetch data from data.json file and display it right?
<img width="1440" alt="Screenshot 2023-10-12 at 11 07 57 AM" src="https://github.com/gbowne1/codebooker/assets/111295843/fafde38f-9929-469c-aa09-7da3e5fd853c">

**Comment by gbowne1** [comment]
@Priyankaa2503 

I get this behaviour too.  It just loads a page with the page spinner after you're logged in.

The original table data came from the data.json file.  Now it's in a ProtectedRoute.  

If I gather right, you need to be logged in, registered, etc. to view the table.  

I haven't been able to figure out what causes this.

**Comment by BlackBond06** [comment]
This behaviour happens because by default, when a user logs in, the home page displays all the books from the db( books were previously gotten from the data.json file in the Library folder), through the FetBooksFromDBfunction. Now since the functionality to retrieve books from dB was added, it replaced populating the UI with books from data.json file. That is, instead of using books from the data.json, the UI is populated with books from the db.

Now since the FetchBookFromDB function is an async function, the response might take some time. Thats where the loading spinner comes in. Instead of showing just a blank screen while waiting for a response, loading spinners or skeleton loader is used to visually tell the user that something is happening, and content is on the way.

Now, after all books are retrieved, the books are rendered to the UI. And if there is nothing in the db, the addbook button should be displayed along with a message that says "No books available, please add a book".

The last part is what is missing from the  code. Right now,  in line 613 of the library.jsx component, it is conditionally displaying the books if the myRows length is > 0, that is if there is atleast one book in the dB. Or else the loading spinner. This is why the loading spinner is perpetually loading without displaying any book. There is currently no book in the db.

What should happen is, when the books are being fetched, display the loading spinner. When the response returns, if there are books(or at least one book in the db) display it, else if no books, show the addbook button, along with a message saying "no books, please add" or something similar.

I can create an issue and make the necessary change to achieve this.

**Comment by BlackBond06** [comment]
@gbowne1 I totally agree with your approach. One question tho: if the user is a new user, and the user access his storage page, shouldnt it be empty as a new user that hasn't added any books to his store ? Hence the message and prompt to add a book.

**Comment by gbowne1** [comment]
Yes correct, in my opinion, a new user would see the global collection of books because.  They would not see any entry in their own library (accessible by going to click on the library button). ideally the global collection would never be empty.  This is also why I proposed a while back we add some method or mechanism to use the json data we already have to seed the database, as its largely been validated.

**Comment by Priyankaa2503** [comment]
@gbowne1 @BlackBond06 thankyou for the detailed explanation.
So for this issue : 
1) Consider seeding the database with default books using existing JSON data to prevent loading issues when the database is empty.
2) In addition to this, the user would also see a "add book" option.

**Comment by gbowne1** [comment]
yes correct @Priyankaa2503

**Comment by BlackBond06** [comment]
@gbowne1 this issue is closed. The PR has been merged. It should be removed from the issues tab.

**Comment by gbowne1** [comment]
Closing as completed
