### ISSUE TITLE
[BUG] CSS property issues with webkit, moz, etc. in index.css and App.css

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/codebooker#185]
In the browser console, We have some artifact issues coming from the global styles in index.css and App.css files that Create React App added, mainly theindex.css

Fixing the global styling in index.css will fix these issues. 

In the browser console, while navigated to the root route, / (or pretty much any other route) in Firefox 116/117 we get: 

Unknown property ‘-moz-osx-font-smoothing’.  Declaration dropped.
Error in parsing value for ‘-webkit-text-size-adjust’.  Declaration dropped.
Unknown pseudo-class or pseudo-element ‘-ms-input-placeholder’.  Ruleset ignored due to bad selector.
Error in parsing value for ‘-webkit-box-align’.  Declaration dropped.

This is mostly a Firefox issue.  Someone with some knowledge of Firefox and webkits could help fix this.

There are also some other keyframe CSS issues, possibly Tailwind CSS might be able to help with this.

**Comment by akshitarora921** [comment]
@gbowne1 Can I take this?

**Comment by gbowne1** [comment]
Yes you can, I will assign you @akshitarora921

**Comment by akshitarora921** [comment]
Since Firefox supports box-shadow so well, it has no reason to keep -moz-box-shadow around. It dropped support for the prefix in version 13
ref: https://stackoverflow.com/questions/19479928/unknown-property-moz-box-shadow-declaration-dropped#:~:text=Since%20Firefox%20supports,of%20WebKit%20browsers.
@gbowne1 Shall I raise a PR to remove all the prefix which are not required?

**Comment by gbowne1** [comment]
yes. Go ahead and submit a PR for that.  @akshitarora921 

We should remove all of the webkit and moz things that are either no longer supported or supported in other ways but cause errors/warnings.
